// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventConnection) DeepCopyInto(out *EventConnection) {
	*out = *in
	out.From = in.From
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]EventEndpoint, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventConnection.
func (in *EventConnection) DeepCopy() *EventConnection {
	if in == nil {
		return nil
	}
	out := new(EventConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventConnections) DeepCopyInto(out *EventConnections) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventConnections.
func (in *EventConnections) DeepCopy() *EventConnections {
	if in == nil {
		return nil
	}
	out := new(EventConnections)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventConnections) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventConnectionsList) DeepCopyInto(out *EventConnectionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventConnections, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventConnectionsList.
func (in *EventConnectionsList) DeepCopy() *EventConnectionsList {
	if in == nil {
		return nil
	}
	out := new(EventConnectionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventConnectionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventConnectionsSpec) DeepCopyInto(out *EventConnectionsSpec) {
	*out = *in
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]EventConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventConnectionsSpec.
func (in *EventConnectionsSpec) DeepCopy() *EventConnectionsSpec {
	if in == nil {
		return nil
	}
	out := new(EventConnectionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventConnectionsStatus) DeepCopyInto(out *EventConnectionsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventConnectionsStatus.
func (in *EventConnectionsStatus) DeepCopy() *EventConnectionsStatus {
	if in == nil {
		return nil
	}
	out := new(EventConnectionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventEndpoint) DeepCopyInto(out *EventEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventEndpoint.
func (in *EventEndpoint) DeepCopy() *EventEndpoint {
	if in == nil {
		return nil
	}
	out := new(EventEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalListener) DeepCopyInto(out *EventExternalListener) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalListener.
func (in *EventExternalListener) DeepCopy() *EventExternalListener {
	if in == nil {
		return nil
	}
	out := new(EventExternalListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventExternalListener) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalListenerList) DeepCopyInto(out *EventExternalListenerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventExternalListener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalListenerList.
func (in *EventExternalListenerList) DeepCopy() *EventExternalListenerList {
	if in == nil {
		return nil
	}
	out := new(EventExternalListenerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventExternalListenerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalListenerSpec) DeepCopyInto(out *EventExternalListenerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalListenerSpec.
func (in *EventExternalListenerSpec) DeepCopy() *EventExternalListenerSpec {
	if in == nil {
		return nil
	}
	out := new(EventExternalListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalListenerStatus) DeepCopyInto(out *EventExternalListenerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalListenerStatus.
func (in *EventExternalListenerStatus) DeepCopy() *EventExternalListenerStatus {
	if in == nil {
		return nil
	}
	out := new(EventExternalListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalProvider) DeepCopyInto(out *EventExternalProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalProvider.
func (in *EventExternalProvider) DeepCopy() *EventExternalProvider {
	if in == nil {
		return nil
	}
	out := new(EventExternalProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventExternalProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalProviderList) DeepCopyInto(out *EventExternalProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventExternalProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalProviderList.
func (in *EventExternalProviderList) DeepCopy() *EventExternalProviderList {
	if in == nil {
		return nil
	}
	out := new(EventExternalProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventExternalProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalProviderSpec) DeepCopyInto(out *EventExternalProviderSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalProviderSpec.
func (in *EventExternalProviderSpec) DeepCopy() *EventExternalProviderSpec {
	if in == nil {
		return nil
	}
	out := new(EventExternalProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalProviderStatus) DeepCopyInto(out *EventExternalProviderStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalProviderStatus.
func (in *EventExternalProviderStatus) DeepCopy() *EventExternalProviderStatus {
	if in == nil {
		return nil
	}
	out := new(EventExternalProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalTopic) DeepCopyInto(out *EventExternalTopic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalTopic.
func (in *EventExternalTopic) DeepCopy() *EventExternalTopic {
	if in == nil {
		return nil
	}
	out := new(EventExternalTopic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventExternalTopic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalTopicList) DeepCopyInto(out *EventExternalTopicList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventExternalTopic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalTopicList.
func (in *EventExternalTopicList) DeepCopy() *EventExternalTopicList {
	if in == nil {
		return nil
	}
	out := new(EventExternalTopicList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventExternalTopicList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalTopicSpec) DeepCopyInto(out *EventExternalTopicSpec) {
	*out = *in
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalTopicSpec.
func (in *EventExternalTopicSpec) DeepCopy() *EventExternalTopicSpec {
	if in == nil {
		return nil
	}
	out := new(EventExternalTopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventExternalTopicStatus) DeepCopyInto(out *EventExternalTopicStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventExternalTopicStatus.
func (in *EventExternalTopicStatus) DeepCopy() *EventExternalTopicStatus {
	if in == nil {
		return nil
	}
	out := new(EventExternalTopicStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFunction) DeepCopyInto(out *EventFunction) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = make([]EventStatement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFunction.
func (in *EventFunction) DeepCopy() *EventFunction {
	if in == nil {
		return nil
	}
	out := new(EventFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventImplementation) DeepCopyInto(out *EventImplementation) {
	*out = *in
	if in.Mediation != nil {
		in, out := &in.Mediation, &out.Mediation
		*out = new(EventMediation)
		(*in).DeepCopyInto(*out)
	}
	if in.Function != nil {
		in, out := &in.Function, &out.Function
		*out = new(EventFunction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventImplementation.
func (in *EventImplementation) DeepCopy() *EventImplementation {
	if in == nil {
		return nil
	}
	out := new(EventImplementation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventMediation) DeepCopyInto(out *EventMediation) {
	*out = *in
	if in.SubscribeFrom != nil {
		in, out := &in.SubscribeFrom, &out.SubscribeFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SendTo != nil {
		in, out := &in.SendTo, &out.SendTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = make([]EventStatement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventMediation.
func (in *EventMediation) DeepCopy() *EventMediation {
	if in == nil {
		return nil
	}
	out := new(EventMediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventMediator) DeepCopyInto(out *EventMediator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventMediator.
func (in *EventMediator) DeepCopy() *EventMediator {
	if in == nil {
		return nil
	}
	out := new(EventMediator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventMediator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventMediatorList) DeepCopyInto(out *EventMediatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventMediator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventMediatorList.
func (in *EventMediatorList) DeepCopy() *EventMediatorList {
	if in == nil {
		return nil
	}
	out := new(EventMediatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventMediatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventMediatorSpec) DeepCopyInto(out *EventMediatorSpec) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = make([]EventImplementation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventMediatorSpec.
func (in *EventMediatorSpec) DeepCopy() *EventMediatorSpec {
	if in == nil {
		return nil
	}
	out := new(EventMediatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventMediatorStatus) DeepCopyInto(out *EventMediatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventMediatorStatus.
func (in *EventMediatorStatus) DeepCopy() *EventMediatorStatus {
	if in == nil {
		return nil
	}
	out := new(EventMediatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventStatement) DeepCopyInto(out *EventStatement) {
	*out = *in
	if in.If != nil {
		in, out := &in.If, &out.If
		*out = new(string)
		**out = **in
	}
	if in.Assign != nil {
		in, out := &in.Assign, &out.Assign
		*out = new(string)
		**out = **in
	}
	if in.Switch != nil {
		in, out := &in.Switch, &out.Switch
		*out = new([]EventStatement)
		if **in != nil {
			in, out := *in, *out
			*out = make([]EventStatement, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new([]EventStatement)
		if **in != nil {
			in, out := *in, *out
			*out = make([]EventStatement, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventStatement.
func (in *EventStatement) DeepCopy() *EventStatement {
	if in == nil {
		return nil
	}
	out := new(EventStatement)
	in.DeepCopyInto(out)
	return out
}
